### ISSUE TITLE
When routing to same page, RouterSessionService.ActiveComponent loses the component reference

### ISSUE THREAD

**Issue by michaelmarcuccio** [ShaunCurtis/CEC.Routing#5]
I seem to have found a bug where if you modify the form, then click the menu item for the same page you are on and "Accept" leaving the page, the RouterSessionService.ActiveComponent will then be set to null even though no route change occurred. If you then modify the form again, the NavigationCancelled will not trigger because the ActiveComponent is null.

It seems like "this" is losing its reference even though the page does not have any events occur such as OnInitialized or anything like that.
`this.RouterSessionService.ActiveComponent = this;` 
This may just be a Blazor routing thing and there may be a way around this but I am not sure how.

This occurs when using Blazor WASM.

**Comment by ShaunCurtis** [comment]
I'll take a look at this in the next couple of days.  I'm travelling at the moment and need a good Internet connection!

**Comment by ShaunCurtis** [comment]
Hi Michael,

This isn't a bug, it's the expected behaviour.  When you route to the same component, what happens is unique to SPA's.  If you provide this navigation possibility, you need to code for it.  The Router raises a *SameComponentNavigation* event that you need to wire into and set the router Service properties again.   Look at my CEC.Blazor or CEC.Weather repositories for more complete implementations where there's a previous and next button on the weather to show how same component navigation can be handled.  There's a whole series of articles on Code Project. 

If this doesn't help, let me know, point me to some code, and I'll try and help.

Shaun
